@startuml
'https://plantuml.com/class-diagram

class Account
class UserInfo
class DeviceConfig

class Account {
    String uuid
    String login
    String password
}

class UserInfo{
    - String uuid
    - String firstName
    - String lastName
    - String email
    - String phoneNumber
    - Date dob
    - Date register
    - Date update
    - Sex sex
    - String country
    - String city
    - String school
    - String grade
    - Role role
}

class DeviceConfig {
    - String deviceId
    - String accountUuid
    - Integer measurementFrequency
    - Integer loverDeviation
    - Integer upperDeviation
    - Integer vibrationDuration
    - Boolean vibrationMode
}

class AuthController{
    + login()
    + logout()
    + register()
}

interface AuthService{
    + login()
    + register()
    - checkUserExist()
}

class AuthServiceImpl{
    + login()
    + register()
    - checkUserExist()
}

class UserRepository {
    + findUserByName()
    + addUser()
}

class DeviceController {
    + getDeviceInfo()
    + setDeviceInfo()
    + setDeviceConfig()
    + getDeviceConfig()
    + storeDeviceMeasurement()
    + getDeviceMeasurement()
}

interface DeviceService {
    + getDeviceInfo()
    + setDeviceInfo()
    + setDeviceConfig()
    + getDeviceConfig()
    + storeDeviceMeasurement()
    + getDeviceMeasurement()
}

class DeviceServiceImpl{
}

class DeviceInfoRepository{
    + getInfoByDeviceId()
    + getDeviceInfo()
}

class DeviceConfigRepository{
    + getDeviceConfig()
    + setDeviceConfig()
}

class DeviceMeasurementRepository{
    + setDeviceMeasurement()
    + getDeviceMeasurement()
}


UserInfo <-- Account
DeviceConfig <-- UserInfo
AuthService <|- AuthServiceImpl
AuthServiceImpl <-- UserRepository
AuthController <-- AuthServiceImpl

DeviceServiceImpl <|- DeviceService
DeviceServiceImpl <-- DeviceConfigRepository
DeviceServiceImpl <-- DeviceInfoRepository
DeviceServiceImpl <-- DeviceMeasurementRepository
DeviceController <-- DeviceServiceImpl

Enum Sex {
    MALE
    FEMALE
}
Enum Role{
    PARENT
    CHILD
}
@enduml